### ISSUE TITLE
How do I capture the whole screen？

### ISSUE THREAD

**Issue by yanxiangrong** [modelflat/zbl#1]

**Comment by modelflat** [comment]
Hi @yanxiangrong ! At the moment this is not supported, but I have plans for implementing it. However I don't have much spare time on my hands at the moment, thus can't give any definite timeline for this feature.

If you need it ASAP, you can implement it yourself. For directions, you can take a look at [screenshot-rs](https://github.com/robmikh/screenshot-rs/blob/main/src/main.rs#L53-L65) which has support for taking whole display screenshots. Porting it to `zbl` should be a matter of introducing a `Capturable` trait, and making `Window` and `Display` implement it; then updating python bindings to accommodate for the change in rust code.

**Comment by modelflat** [comment]
@yanxiangrong actually, I've taken some time to implement it today, and it seems to work. Feel free to check it out in version 0.1.0!

**Comment by modelflat** [comment]
alright, so I finalized implementation and fixed a couple of bugs related to monitor scaling. This functionality is out with `v0.1.1`. Use `python -m zbl --display-id 0` or `with Capture(display_id=0) as capture: ...` to capture the entire screen. Same is available in Rust interface.
