### ISSUE TITLE
RuntimeError: windows api error: Could not capture the given window. (0x80070057)

### ISSUE THREAD

**Issue by leonsama** [modelflat/zbl#2]
I'm trying to captrue a windows that contains transparency such as "FolderView".

Here is my code.

```python
import ctypes
import win32gui
import win32con
import pywintypes


def enum_user_windows_cb(hwnd, lParam):
    wflags = win32gui.GetWindowLong(hwnd, win32con.GWL_STYLE)
    if not (wflags & win32con.WS_VISIBLE):
        return True
    sndWnd = win32gui.FindWindowEx(hwnd, None, "SHELLDLL_DefView", None)
    if not sndWnd:
        return True
    targetWnd = win32gui.FindWindowEx(sndWnd, None, "SysListView32", "FolderView")
    if not targetWnd:
        return True
    resultHwnd = ctypes.cast(lParam, ctypes.POINTER(ctypes.c_void_p))
    resultHwnd.contents.value = targetWnd
    return False


def findDesktopIconHwnd() -> int:
    resultHwnd = ctypes.c_void_p()
    try:
        win32gui.EnumWindows(enum_user_windows_cb, ctypes.addressof(resultHwnd))
    except pywintypes.error:
        pass
    finally:
        return resultHwnd.value

from zbl import Capture

if __name__ == '__main__':
    hwnd = findDesktopIconHwnd()
    print(hwnd)
    with Capture(window_handle=int(hwnd)) as cap:
        frame = next(cap.frames())
        print(frame.shape)
```

The following error occurs when this code is run:

```
...
  File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\zbl\__init__.py", line 35, in __init__
    self._inner = _NativeCapture(window_name, window_handle, display_id, capture_cursor)
RuntimeError: windows api error: Could not capture the given window. (0x80070057)
```

Is there any way to make the code run correctly?

**Comment by leonsama** [comment]
@modelflat  Hello modelflat, it seems that WGI may not be able to recognize windows with the `WS_EX_TOOLWINDOW` style. One possible solution is to manually remove the `WS_EX_TOOLWINDOW` style from the target window, but this is an undocumented approach and could potentially result in some side effects. What are your thoughts on this?

**Comment by modelflat** [comment]
Hi @SolomonLeon !

Regarding your original question: I'm not sure which window you are trying to capture (`findDesktopIconHwnd` seems to be finding the Desktop background window? I might be wrong), but the cause of the error is most likely that it is non-capturable by the WGI.

> One possible solution is to manually remove the WS_EX_TOOLWINDOW style from the target window, but this is an undocumented approach and could potentially result in some side effects

I'd prefer to leave this as a responsibility on the consumer of `zbl` to ensure the window is capturable. However, I'll try to add more descriptive errors for easier debugging.
